Output demo.gif

Set FontSize 20
Set Width 800
Set Height 800

Set FontFamily "FiraCode Nerd Font"
Set TypingSpeed 80ms

Type "lsd"
Enter

Sleep 300ms

Type "cat Structfile.yml"
Enter

Sleep 800ms

Type "struct create"
Enter

Sleep 600ms

Type "lsd --tree"
Enter

Sleep 1000ms

Type "cat root-file folder-a/a.txt"
Enter

Sleep 1000ms

Type "struct destroy"
Enter

Sleep 400ms

Type "lsd"
Enter

Sleep 500ms