name: vhs
on:
  push:
    paths:
      - vhs.tape
      - '*.yml'
jobs:
  vhs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Installing lsd and bat...
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo apt install lsd bat -y
          alias cat=batcat --pager=no
          alias struct=./struct
      

      - name: Building executable...
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cargo build
          cd ./example/
          mv ../target/debug/struct .
      
      - name: Recording tape...
        uses: charmbracelet/vhs-action@main
        with:
          path: 'vhs.tape'

      - name: Commiting GIF...
        uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update generated VHS GIF
          branch: main
          commit_user_name: vhs-action 📼
          commit_user_email: actions@github.com
          commit_author: vhs-action 📼 <actions@github.com>
          file_pattern: '*.gif'